version: '3.8'

services:
  dev:
    image: docker.io/library/nginx:1.21.4
    init: true
    volumes: 
      - ./html:/usr/share/nginx/html:cached
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
